apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-preprod
  namespace: argocd
spec:
  project: preprod
  source:
    repoURL: https://github.com/joshbates03/platform-lab
    targetRevision: HEAD
    path: apps/overlays/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
